### ISSUE TITLE
Multiple Timeout Exceptions During Initial Data Collection

### ISSUE THREAD

**Issue by ruyl** [Comp413-F18/DatelineRice2.0#40]
While adding international coverage support, I have gotten error messages similar to this coming from unrelated parts of the code that seems to be due to some sort of timeout. I feel like there might be a better way to deal with timeouts like this if this isn't simply somehow our error anyway:

```
Collecting articles...
newsriver{"mediaOutletName": "Chemie [chemie.de]", "url": "http://www.chemie.de/news/162161/effektiverer-katalysator-mit-licht.html?WT.mc_id=ca0065", "headline": "Effektiverer Katalysator mit Licht", "language": "unknown", "locale": "unknown", "authors": [], "mediaType": "unknown", "category": "unknown", "coverageDate": "unknown"}
newsriver{"mediaOutletName": "Workplace Insight", "url": "http://workplaceinsight.net/refurbished-industrial-buildings-provide-perfect-modern-workplaces/", "headline": "Refurbished industrial buildings provide perfect modern workplaces", "language": "unknown", "locale": "unknown", "authors": ["Mark Eltringham"], "mediaType": "unknown", "category": "unknown", "coverageDate": "unknown"}
Traceback (most recent call last):
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/ruyl/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.dailyexcelsior.com', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 89, in <module>
    search_articles = pull_from_search()
  File "run.py", line 22, in pull_from_search
    return fra.find()
  File "/mnt/c/Users/Nicholas/Documents/Rice University/Senior Year/Fall 2018/COMP 413/Dateline2/DatelineRice2.0/DataCollection/collecting_data/pull_search.py", line 41, in find
    source = requests.get(url, timeout=5)
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ruyl/.local/lib/python3.5/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.dailyexcelsior.com', port=80): Read timed out. (read timeout=5)
```

**Comment by nithinara** [comment]
Once my changes get merged, and I can test this, I haven't been getting those errors, but I can put a try/catch in to stop this from happening.

**Comment by nithinara** [comment]
It looks like I handled this? As I have not gotten this error since I added in a try catch, but there are probably other others that webhose/newsrivers API can call that I will have to handle as well.
